version: '2.4'

services:

    pedraMoura-nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: pedraMoura-nginx-proxy
        restart: on-failure
        privileged: true
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        mem_limit: 128M
    
    site2:
        image: httpd:2.4
        container_name: site2
        environment:
            - VIRTUAL_HOST=site.pedramoura.local
        hostname: site.pedramoura.local
        depends_on:
            - pedraMoura-nginx-proxy
        volumes:
            - ./site/html:/usr/local/apache2/htdocs
